### ISSUE TITLE
Figure out format for sampling profiler data

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/rbkit#121]
Here are my thoughts : 

1. Use a dictionary for storing strings in the sampling data (like filenames) and send that as the first payload. This will reduce size of payloads to be sent afterwords. See #120.
2.  Each sample will be of this format : 

```ruby
{
  timestamp: <timestamp in ms>,
  event_type: 'cpu_sample',
  correlation_id: <id indicating event this message is part of>,
  complete_message_count: <total number of messages this event is split into>,
  payload: [
    {
      timestamp: <timestamp when sample was collected>,
      frames: [
        {
          method_name: <name of method >,
          file: <filename>,
          line: <line no>,
          classpath: <Class path of method>,
          singleton_method: <true/false>
        }, #Frame 1
        ...
      ]
    }, #Sample 1
    ...
  ] # As many samples as we can fit in this payload
}
```

**Comment by emilsoman** [comment]
We'll not implement any string dictionary in the first cut.

**Comment by emilsoman** [comment]
I made a few changes after working on this feature a bit : 

```yaml
{
  event_type: cpu_samples
  timestamp: <timestamp in milliseconds>,
  correlation_id: <ID_INDICATING_EVENT_THIS_MESSAGE_IS_PART_OF>,
  sample_count: <total number of samples collected>,
  payload: [
    {
      timestamp: <timestamp when sample was collected>,
      frames: [
        {
          method_name: <name of method >,
          label: <method label (See below for details)>,
          file: <filename>,
          line: <line no>,
          singleton_method: <1/0>,
          thread_id: <thread id>
        }, #Frame 1
        ...
      ]
    }, #Sample 1
    ...
  ] # As many samples as we can fit in this payload
}
```

Ruby VM gives us something called a "full label" which will give us many details
about each frame in the call stack. Some examples:

```ruby
"block (2 levels) in SampleClass#foobar" # foobar is an instance method of SampleClass. The frame is 2 blocks deep inside foobar.
"#{obj.inspect}.zab" # Frame is in zab, a singleton method defined on an object obj
"SampleClass#baz" # Frame is in baz, an instance method defined in SampleClass
"SampleClass.bar" # Frame is in bar, a class method defined in SampleClass
```

**Comment by emilsoman** [comment]
@iffyuva @ishankhare07 Since we want to send samples as and when we collect them instead of waiting for the sampling to stop, we won't have a correlation_id or sample_count . We'll use the following format and send only one sample in each event (which will still be aggregated in an event_collection message ) : 

```yaml
{
  event_type: cpu_sample
  timestamp: <timestamp in milliseconds>,
  payload: [
    {
      method_name: <name of method >,
      label: <method label (See below for details)>,
      file: <filename>,
      line: <line no>,
      singleton_method: <true/false>,
      thread_id: <thread id>
    }, #Frame 1
    ...
  ] # Array of frames in the sample
}
```
